language: objective-c
osx_image: xcode7.3
script: xcodebuild -project Plastic.xcodeproj -scheme Plastic -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' test | xcpretty
