language: objective-c
osx_image: xcode7.3
script: xcodebuild -project Plastic.xcodeproj -scheme PlasticTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
